# Generated by Django 5.1.3 on 2026-02-06 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "escandallo_app",
            "0002_alter_escandallo_rendimiento_escandallolinea_and_more",
        ),
        ("inventario_app", "0004_alter_apliconteo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Produccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "responsable",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "rendimiento_real",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "escandallo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="producciones",
                        to="escandallo_app.escandallo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProduccionLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad_real", models.DecimalField(decimal_places=3, max_digits=10)),
                ("unidad", models.CharField(default="g", max_length=20)),
                (
                    "merma",
                    models.DecimalField(decimal_places=3, default=0, max_digits=10),
                ),
                (
                    "ingrediente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
                (
                    "produccion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="produccion.produccion",
                    ),
                ),
            ],
        ),
    ]
