# Generated by Django 5.1.3 on 2026-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produccionlinea",
            name="cantidad_teorica",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
