# Generated by Django 5.1.3 on 2026-02-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produccion", "0002_produccionlinea_cantidad_teorica"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produccion",
            options={
                "ordering": ["-fecha"],
                "verbose_name": "Producción",
                "verbose_name_plural": "Producciones",
            },
        ),
        migrations.AlterModelOptions(
            name="produccionlinea",
            options={
                "verbose_name": "Línea de producción",
                "verbose_name_plural": "Líneas de producción",
            },
        ),
    ]
