# Generated by Django 5.2.10 on 2026-02-27 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "inventario_app",
            "0013_proveedor_activo_proveedor_cif_proveedor_descuento_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CondicionPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("dias", models.PositiveIntegerField(default=0)),
                (
                    "descuento_pronto_pago",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("dias_pronto_pago", models.PositiveIntegerField(default=0)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AlbaranCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_recepcion", models.DateField()),
                (
                    "numero_albaran",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONFIRMADO", "Confirmado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "iva_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.proveedor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AlbaranCompraLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_recibida",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "total_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("devuelto", models.BooleanField(default=False)),
                (
                    "motivo_devolucion",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "albaran",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="appcompras.albarancompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FacturaCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_factura", models.DateField()),
                ("numero_factura", models.CharField(max_length=50)),
                (
                    "descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "importe_descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subtotal_antes_descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "iva_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fecha_vencimiento", models.DateField()),
                (
                    "estado_factura",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("CONTABILIZADA", "Contabilizada"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "estado_pago",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("PARCIAL", "Parcialmente pagada"),
                            ("PAGADA", "Pagada"),
                            ("VENCIDA", "Vencida"),
                        ],
                        default="PENDIENTE",
                        max_length=20,
                    ),
                ),
                (
                    "importe_pendiente",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "condicion_pago",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="appcompras.condicionpago",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.proveedor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="albarancompra",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albaranes",
                to="appcompras.facturacompra",
            ),
        ),
        migrations.CreateModel(
            name="FacturaCompraLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "total_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "factura",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="appcompras.facturacompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PedidoCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_pedido", models.DateField()),
                ("fecha_prevista", models.DateField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("BORRADOR", "Borrador"),
                            ("ENVIADO", "Enviado"),
                            ("RECIBIDO_PARCIAL", "Recibido parcial"),
                            ("RECIBIDO_TOTAL", "Recibido total"),
                            ("CANCELADO", "Cancelado"),
                        ],
                        default="BORRADOR",
                        max_length=20,
                    ),
                ),
                (
                    "subtotal_antes_descuento",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "importe_descuento_global",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "iva_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "proveedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.proveedor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="albarancompra",
            name="pedido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albaranes",
                to="appcompras.pedidocompra",
            ),
        ),
        migrations.CreateModel(
            name="PedidoCompraLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad_pedida",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "precio_unitario",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "descuento_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "iva",
                    models.DecimalField(decimal_places=2, default=21, max_digits=5),
                ),
                (
                    "total_linea",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="appcompras.pedidocompra",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
            ],
        ),
    ]
