# Generated by Django 5.1.3 on 2026-02-27 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appcompras", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pedidocompra",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="pedidocompralinea",
            name="cantidad_recibida",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="pedidocompralinea",
            name="estado_linea",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONFIRMADA", "Confirmada"),
                    ("PARCIAL", "Parcial"),
                    ("COMPLETA", "Completa"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="pedidocompralinea",
            name="iva_importe",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="pedidocompralinea",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="pedidocompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONFIRMADO", "Confirmado"),
                    ("PARCIALMENTE_RECIBIDO", "Parcialmente recibido"),
                    ("CERRADO", "Cerrado"),
                    ("CANCELADO", "Cancelado"),
                ],
                default="BORRADOR",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="pedidocompralinea",
            name="total_linea",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
