# Generated by Django 5.1.3 on 2026-03-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appcompras", "0002_alter_pedidocompra_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="albarancompra",
            options={
                "permissions": [
                    (
                        "puede_reabrir_albaranes_compra",
                        "Puede reabrir albaranes de compra",
                    )
                ]
            },
        ),
        migrations.AlterModelOptions(
            name="facturacompra",
            options={
                "permissions": [
                    ("puede_anular_facturas_compra", "Puede anular facturas de compra")
                ]
            },
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="fecha_vencimiento",
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="importe_pendiente",
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="iva_total",
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="subtotal_antes_descuento",
        ),
        migrations.RemoveField(
            model_name="facturacompra",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="facturacompralinea",
            name="descuento_linea",
        ),
        migrations.RemoveField(
            model_name="facturacompralinea",
            name="iva",
        ),
        migrations.RemoveField(
            model_name="facturacompralinea",
            name="total_linea",
        ),
        migrations.AddField(
            model_name="facturacompra",
            name="importe_impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="facturacompra",
            name="importe_subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="facturacompralinea",
            name="importe_descuento",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="facturacompralinea",
            name="importe_impuestos",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name="facturacompralinea",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="descuento_global",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="estado_factura",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONTABILIZADA", "Contabilizada"),
                    ("ANULADA", "Anulada"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="importe_descuento_global",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="facturacompra",
            name="total",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name="facturacompralinea",
            name="cantidad",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="facturacompralinea",
            name="precio_unitario",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
