# Generated by Django 5.1.3 on 2026-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appcompras", "0003_alter_albarancompra_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturacompralinea",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
