# Generated by Django 5.1.3 on 2026-03-04 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appcompras", "0004_facturacompralinea_iva"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturacompra",
            name="albaranes",
            field=models.ManyToManyField(
                blank=True,
                related_name="facturas_asociadas",
                to="appcompras.albarancompra",
            ),
        ),
        migrations.AlterField(
            model_name="albarancompra",
            name="estado",
            field=models.CharField(
                choices=[
                    ("BORRADOR", "Borrador"),
                    ("CONFIRMADO", "Confirmado"),
                    ("FACTURADO", "Facturado"),
                ],
                default="BORRADOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="albarancompra",
            name="factura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="albaranes_directos",
                to="appcompras.facturacompra",
            ),
        ),
        migrations.AlterField(
            model_name="facturacompralinea",
            name="iva",
            field=models.DecimalField(decimal_places=2, default=21, max_digits=5),
        ),
        migrations.AlterField(
            model_name="pedidocompralinea",
            name="iva",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
