# Generated by Django 5.1.3 on 2026-03-10 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appcompras",
            "0005_facturacompra_albaranes_alter_albarancompra_estado_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="facturacompra",
            name="condicion_pago",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="appcompras.condicionpago",
            ),
        ),
    ]
