# Generated by Django 5.1.3 on 2026-02-04 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventario_app", "0004_alter_apliconteo_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Escandallo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                ("descripcion", models.TextField(blank=True, null=True)),
                (
                    "rendimiento",
                    models.DecimalField(decimal_places=2, default=1, max_digits=6),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EscandalloItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=3, max_digits=10)),
                (
                    "merma",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "escandallo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="escandallo_app.escandallo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
            ],
        ),
    ]
