# Generated by Django 5.1.3 on 2026-02-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escandallo_app", "0001_initial"),
        ("inventario_app", "0004_alter_apliconteo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escandallo",
            name="rendimiento",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.CreateModel(
            name="EscandalloLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unidad", models.CharField(default="g", max_length=20)),
                (
                    "escandallo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="escandallo_app.escandallo",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="EscandalloItem",
        ),
    ]
