# Generated by Django 5.1.3 on 2026-03-05 10:18

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "escandallo_app",
            "0002_alter_escandallo_rendimiento_escandallolinea_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="escandallo",
            options={
                "verbose_name": "Escandallo",
                "verbose_name_plural": "Escandallos",
            },
        ),
        migrations.AlterModelOptions(
            name="escandallolinea",
            options={
                "verbose_name": "Línea de escandallo",
                "verbose_name_plural": "Líneas de escandallo",
            },
        ),
        migrations.AddField(
            model_name="escandallo",
            name="precio_venta_sin_iva",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta sin IVA por ración/unidad.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="escandallolinea",
            name="merma_porcentaje",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Porcentaje de merma de este ingrediente.",
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("100.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="escandallolinea",
            name="precio_coste",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Precio de coste unitario del producto en el momento del escandallo.",
                max_digits=10,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="escandallo",
            name="nombre",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="escandallo",
            name="rendimiento",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.00"),
                help_text="Número de raciones o unidades que produce este escandallo.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="escandallolinea",
            name="cantidad",
            field=models.DecimalField(
                decimal_places=3,
                help_text="Cantidad BRUTA utilizada (antes de merma).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.000"))],
            ),
        ),
        migrations.AlterField(
            model_name="escandallolinea",
            name="unidad",
            field=models.CharField(
                default="g",
                help_text="Unidad de medida (g, kg, ml, l, ud, etc.).",
                max_length=20,
            ),
        ),
    ]
