# Generated by Django 5.0.9 on 2026-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("escandallo_app", "0003_alter_escandallo_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escandallolinea",
            name="precio_coste",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de coste unitario del producto en el momento del escandallo.",
                max_digits=10,
            ),
        ),
    ]
