# Generated by Django 5.1.3 on 2026-02-08 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CuentaContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("es_activo", models.BooleanField(default=False)),
                ("es_pasivo", models.BooleanField(default=False)),
                ("es_pyg", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Cuentas contables",
                "ordering": ["codigo"],
            },
        ),
        migrations.CreateModel(
            name="Diario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Diario contable",
                "verbose_name_plural": "Diarios contables",
            },
        ),
        migrations.CreateModel(
            name="Asiento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "referencia",
                    models.CharField(
                        blank=True,
                        help_text="Referencia externa (ej: ajuste inventario, factura, etc.)",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "diario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="asientos",
                        to="contabilidad_app.diario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asiento contable",
                "verbose_name_plural": "Asientos contables",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="AsientoLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "debe",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "haber",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "asiento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="contabilidad_app.asiento",
                    ),
                ),
                (
                    "cuenta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad_app.cuentacontable",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de asiento",
                "verbose_name_plural": "Líneas de asiento",
            },
        ),
    ]
