# Generated by Django 5.2.10 on 2026-02-26 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contabilidad_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Categoría",
                "verbose_name_plural": "Categorías",
            },
        ),
        migrations.CreateModel(
            name="IVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                "verbose_name": "IVA",
                "verbose_name_plural": "IVA",
            },
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("cif", models.CharField(blank=True, max_length=20, null=True)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("direccion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "persona_contacto",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("forma_pago", models.CharField(blank=True, max_length=100, null=True)),
                ("plazo_pago", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "descuento",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "referencia_interna",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("activo", models.BooleanField(default=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Proveedor",
                "verbose_name_plural": "Proveedores",
            },
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("abreviatura", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
            },
        ),
        migrations.AlterModelOptions(
            name="asiento",
            options={"verbose_name": "Asiento", "verbose_name_plural": "Asientos"},
        ),
        migrations.AlterModelOptions(
            name="cuentacontable",
            options={
                "verbose_name": "Cuenta contable",
                "verbose_name_plural": "Cuentas contables",
            },
        ),
        migrations.AlterModelOptions(
            name="diario",
            options={"verbose_name": "Diario", "verbose_name_plural": "Diarios"},
        ),
        migrations.RemoveField(
            model_name="asiento",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="cuentacontable",
            name="es_activo",
        ),
        migrations.RemoveField(
            model_name="cuentacontable",
            name="es_pasivo",
        ),
        migrations.RemoveField(
            model_name="cuentacontable",
            name="es_pyg",
        ),
        migrations.AlterField(
            model_name="asiento",
            name="descripcion",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asiento",
            name="diario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="contabilidad_app.diario",
            ),
        ),
        migrations.AlterField(
            model_name="asiento",
            name="referencia",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="asientolinea",
            name="descripcion",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="ConteoSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("conteo", "Conteo"),
                            ("revision", "Revisión"),
                            ("auditoria", "Auditoría"),
                        ],
                        default="conteo",
                        max_length=20,
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("en_revision", "En revisión"),
                            ("cerrada", "Cerrada"),
                            ("aprobada", "Aprobada"),
                            ("aplicada", "Aplicada"),
                            ("reabierta", "Reabierta"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                ("fecha_aplicacion", models.DateTimeField(blank=True, null=True)),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                ("fecha_reapertura", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sesiones_conteo_contabilidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_cierre",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cierres_conteo_contabilidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "usuario_reapertura",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reaperturas_conteo_contabilidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de conteo",
                "verbose_name_plural": "Sesiones de conteo",
            },
        ),
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incremento", "Incremento de inventario"),
                            ("disminucion", "Disminución de inventario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("debe_cuenta", models.CharField(max_length=50)),
                ("haber_cuenta", models.CharField(max_length=50)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asientos_inventario_contabilidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion_conteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos",
                        to="contabilidad_app.conteosesion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_interno", models.CharField(max_length=50, unique=True)),
                ("nombre_interno", models.CharField(max_length=150)),
                (
                    "nombre_proveedor",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contabilidad_app.categoria",
                    ),
                ),
                (
                    "iva",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contabilidad_app.iva",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contabilidad_app.proveedor",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad_app.unidadmedida",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="ConteoLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("precio_coste", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "stock_teorico",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_contado",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("motivo", models.CharField(blank=True, max_length=200, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=200, null=True)),
                ("fecha_modifica", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario_modifica",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="modificaciones_conteo_contabilidad",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="contabilidad_app.conteosesion",
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contabilidad_app.producto",
                    ),
                ),
            ],
        ),
    ]
