# Generated by Django 5.0.9 on 2026-02-01 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="IVA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("porcentaje", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Proveedor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("telefono", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnidadMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("abreviatura", models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_interno", models.CharField(max_length=50, unique=True)),
                ("nombre_interno", models.CharField(max_length=150)),
                (
                    "nombre_proveedor",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "codigo_barras",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "stock_minimo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "stock_actual",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario_app.categoria",
                    ),
                ),
                (
                    "iva",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario_app.iva",
                    ),
                ),
                (
                    "proveedor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario_app.proveedor",
                    ),
                ),
                (
                    "unidad_medida",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="inventario_app.unidadmedida",
                    ),
                ),
            ],
        ),
    ]
