# Generated by Django 5.1.3 on 2026-02-02 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apliconteo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conteo_fisico",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad contada físicamente en almacén.",
                        max_digits=10,
                    ),
                ),
                (
                    "stock_teorico",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Stock teórico en el momento del conteo.",
                        max_digits=10,
                    ),
                ),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="conteo_fisico - stock_teorico.",
                        max_digits=10,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="conteos_fisicos",
                        to="inventario_app.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Conteo físico",
                "verbose_name_plural": "Conteos físicos",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="Aplinventario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENTRADA", "Entrada"),
                            ("SALIDA", "Salida"),
                            (
                                "REVALORIZACION",
                                "Revalorización del último precio de coste",
                            ),
                            ("AJUSTE", "Ajuste por conteo físico"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "motivo_salida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("VENTA", "Venta"),
                            ("ESCANDALLO", "Escandallo / Producción"),
                            ("MERMA", "Merma"),
                            ("ROTURA", "Rotura"),
                            ("CONSUMO", "Consumo interno"),
                            ("CADUCIDAD", "Caducidad"),
                            ("OTRO", "Otro"),
                        ],
                        help_text="Solo se usa cuando el movimiento es una salida.",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Cantidad del movimiento.",
                        max_digits=10,
                    ),
                ),
                (
                    "nuevo_precio_coste",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Nuevo precio de coste unitario (solo en revalorizaciones).",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("comentario", models.TextField(blank=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="movimientos",
                        to="inventario_app.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de inventario",
                "verbose_name_plural": "Movimientos de inventario",
                "ordering": ["-fecha"],
            },
        ),
    ]
