# Generated by Django 5.1.3 on 2026-02-02 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0002_apliconteo_aplinventario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apliconteo",
            name="diferencia",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="conteo_fisico - stock_teorico.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="apliconteo",
            name="stock_teorico",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Stock teórico en el momento del conteo.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="categoria",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario_app.categoria",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="iva",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario_app.iva",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="proveedor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario_app.proveedor",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventario_app.unidadmedida",
            ),
        ),
    ]
