# Generated by Django 5.2.10 on 2026-02-04 12:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0003_alter_apliconteo_diferencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apliconteo",
            options={
                "ordering": ["-fecha_conteo"],
                "verbose_name": "Conteo de inventario",
                "verbose_name_plural": "Conteos de inventario",
            },
        ),
        migrations.RenameField(
            model_name="apliconteo",
            old_name="fecha",
            new_name="fecha_conteo",
        ),
        migrations.RemoveField(
            model_name="apliconteo",
            name="comentario",
        ),
        migrations.RemoveField(
            model_name="apliconteo",
            name="conteo_fisico",
        ),
        migrations.RemoveField(
            model_name="apliconteo",
            name="diferencia",
        ),
        migrations.RemoveField(
            model_name="apliconteo",
            name="stock_teorico",
        ),
        migrations.AddField(
            model_name="apliconteo",
            name="cantidad_contada",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apliconteo",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="apliconteo",
            name="producto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="conteos",
                to="inventario_app.producto",
            ),
        ),
        migrations.AlterField(
            model_name="apliconteo",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
