# Generated by Django 5.1.3 on 2026-02-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0004_alter_apliconteo_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categoria",
            options={"verbose_name": "Categoría", "verbose_name_plural": "Categorías"},
        ),
        migrations.AlterModelOptions(
            name="iva",
            options={"verbose_name": "IVA", "verbose_name_plural": "IVA"},
        ),
        migrations.AlterModelOptions(
            name="producto",
            options={"verbose_name": "Producto", "verbose_name_plural": "Productos"},
        ),
        migrations.AlterModelOptions(
            name="proveedor",
            options={"verbose_name": "Proveedor", "verbose_name_plural": "Proveedores"},
        ),
        migrations.AlterModelOptions(
            name="unidadmedida",
            options={
                "verbose_name": "Unidad de medida",
                "verbose_name_plural": "Unidades de medida",
            },
        ),
        migrations.AddField(
            model_name="apliconteo",
            name="confirmado",
            field=models.BooleanField(default=False),
        ),
    ]
