# Generated by Django 5.2.10 on 2026-02-09 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0005_alter_categoria_options_alter_iva_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConteoSesion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("abierta", "Abierta"),
                            ("cerrada", "Cerrada"),
                            ("aplicada", "Aplicada"),
                        ],
                        default="abierta",
                        max_length=20,
                    ),
                ),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión de conteo",
                "verbose_name_plural": "Sesiones de conteo",
            },
        ),
        migrations.CreateModel(
            name="ConteoLinea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stock_teorico", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_contado", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "diferencia",
                    models.DecimalField(
                        decimal_places=2, editable=False, max_digits=10
                    ),
                ),
                ("motivo", models.CharField(blank=True, max_length=255, null=True)),
                ("ubicacion", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
                (
                    "sesion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lineas",
                        to="inventario_app.conteosesion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Línea de conteo",
                "verbose_name_plural": "Líneas de conteo",
            },
        ),
        migrations.DeleteModel(
            name="Apliconteo",
        ),
    ]
