# Generated by Django 5.1.3 on 2026-02-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0006_conteosesion_conteolinea_delete_apliconteo"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conteosesion",
            old_name="fecha",
            new_name="fecha_creacion",
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="codigo_barras",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="valor_diferencia",
            field=models.DecimalField(
                decimal_places=2, default=0, editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="asiento_contable_faltantes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="asiento_contable_sobrantes",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="fecha_aplicacion",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="nombre",
            field=models.CharField(default=" ", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("conteo", "Conteo"),
                    ("revision", "Revisión"),
                    ("auditoria", "Auditoría"),
                ],
                default="conteo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="conteosesion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierta", "Abierta"),
                    ("en_revision", "En revisión"),
                    ("cerrada", "Cerrada"),
                    ("aprobada", "Aprobada"),
                    ("aplicada", "Aplicada"),
                ],
                default="abierta",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="Aplinventario",
        ),
    ]
