# Generated by Django 5.1.3 on 2026-02-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0007_rename_fecha_conteosesion_fecha_creacion_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conteolinea",
            name="valor_diferencia",
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="importe_contado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="importe_diferencia",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="importe_teorico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="precio_coste",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
