# Generated by Django 5.1.3 on 2026-02-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0008_remove_conteolinea_valor_diferencia_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conteolinea",
            name="diferencia",
        ),
        migrations.RemoveField(
            model_name="conteolinea",
            name="importe_contado",
        ),
        migrations.RemoveField(
            model_name="conteolinea",
            name="importe_diferencia",
        ),
        migrations.RemoveField(
            model_name="conteolinea",
            name="importe_teorico",
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="motivo",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="precio_coste",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="stock_contado",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="stock_teorico",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="conteolinea",
            name="ubicacion",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
