# Generated by Django 5.1.3 on 2026-02-14 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0009_remove_conteolinea_diferencia_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="conteolinea",
            options={},
        ),
        migrations.RemoveField(
            model_name="conteosesion",
            name="asiento_contable_faltantes",
        ),
        migrations.RemoveField(
            model_name="conteosesion",
            name="asiento_contable_sobrantes",
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="fecha_cierre",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="fecha_reapertura",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="usuario_cierre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cierres_conteo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="conteosesion",
            name="usuario_reapertura",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reaperturas_conteo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="conteosesion",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierta", "Abierta"),
                    ("en_revision", "En revisión"),
                    ("cerrada", "Cerrada"),
                    ("aprobada", "Aprobada"),
                    ("aplicada", "Aplicada"),
                    ("reabierta", "Reabierta"),
                ],
                default="abierta",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AsientoContable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("incremento", "Incremento de inventario"),
                            ("disminucion", "Disminución de inventario"),
                        ],
                        max_length=20,
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                ("debe_cuenta", models.CharField(max_length=50)),
                ("haber_cuenta", models.CharField(max_length=50)),
                ("importe", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                (
                    "sesion_conteo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asientos",
                        to="inventario_app.conteosesion",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
