# Generated by Django 5.1.3 on 2026-02-15 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0010_alter_conteolinea_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="unidad_medida",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventario_app.unidadmedida",
            ),
        ),
    ]
