# Generated by Django 5.1.3 on 2026-02-16 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0011_alter_producto_codigo_barras_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="conteolinea",
            name="fecha_modifica",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conteolinea",
            name="usuario_modifica",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modificaciones_conteo",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="codigo_barras",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
