# Generated by Django 5.1.3 on 2026-02-25 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0012_conteolinea_fecha_modifica_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proveedor",
            name="activo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="cif",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="descuento",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="direccion",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="forma_pago",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="persona_contacto",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="plazo_pago",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="proveedor",
            name="referencia_interna",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
