# Generated by Django 5.1.3 on 2026-02-28 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventario_app",
            "0013_proveedor_activo_proveedor_cif_proveedor_descuento_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MovimientoStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("entrada", "Entrada"),
                            ("salida", "Salida"),
                            ("ajuste_positivo", "Ajuste positivo"),
                            ("ajuste_negativo", "Ajuste negativo"),
                            ("produccion_consumo", "Consumo producción"),
                            ("produccion_entrada", "Entrada producto final"),
                            ("venta", "Venta"),
                            ("devolucion", "Devolución"),
                        ],
                        max_length=30,
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_antes", models.DecimalField(decimal_places=2, max_digits=10)),
                ("stock_despues", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "coste_unitario",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                (
                    "coste_total",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=12, null=True
                    ),
                ),
                ("referencia", models.CharField(blank=True, max_length=255, null=True)),
                ("origen", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("notas", models.TextField(blank=True, null=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventario_app.producto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Movimiento de stock",
                "verbose_name_plural": "Movimientos de stock",
                "ordering": ["-fecha"],
            },
        ),
    ]
