# Generated by Django 5.1.3 on 2026-02-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0014_movimientostock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="metodo_valoracion",
            field=models.CharField(
                choices=[
                    ("ULTIMO_COSTE", "Último coste"),
                    ("COSTE_MEDIO", "Coste medio ponderado"),
                ],
                default="ULTIMO_COSTE",
                max_length=20,
            ),
        ),
    ]
