# Generated by Django 5.0.9 on 2026-03-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventario_app", "0015_producto_metodo_valoracion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movimientostock",
            name="tipo",
            field=models.CharField(
                choices=[
                    ("entrada", "Entrada"),
                    ("salida", "Salida"),
                    ("ajuste_positivo", "Ajustte positivo"),
                    ("ajuste_negativo", "Ajuste negativo"),
                    ("produccion_consumo", "Consumo producción"),
                    ("produccion_entrada", "Entrada producto final"),
                    ("venta", "Venta"),
                    ("devolucion", "Devolución"),
                ],
                max_length=30,
            ),
        ),
    ]
